export { DEFAULT_NAME, defaultLinks, EMPTY_COLOR } from './defaults'
export { brandIcons } from './icons'
export type { BrandIcon } from './icons'
export { resolveLinks } from './resolve'
export type { SocialLink } from './types'
